// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"go_demo/xwire/baz"
	"go_demo/xwire/foo"
)

// Injectors from main.go:

func initializeBaz(ctx context.Context) (baz.Ss, error) {
	fooFoo := foo.ProvideFoo()
	bar := baz.ProvideBar(fooFoo)
	bazBaz, err := baz.ProvideBaz(ctx, bar)
	if err != nil {
		return baz.Ss{}, err
	}
	ss, err := baz.ProvideTi(ctx, bazBaz)
	if err != nil {
		return baz.Ss{}, err
	}
	return ss, nil
}
